- name: Test Host Connection
  hosts: production
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: "Deploying under user: {{ admin_user}}"
- name: Build and Run Docker Containers
  hosts: production
  tasks:
    - name: Clone repository
      ansible.builtin.git:
        repo: "{{ project_git_repo }}"
        dest: "{{ project_source_path }}"
        version: "{{ repo_branch }}"
        accept_hostkey: true
        force: true
      ignore_errors: true
    - name: Run docker-compose
      ansible.builtin.command: docker compose up -d --remove-orphans --force-recreate
      args:
        chdir: "{{ project_source_path }}"
    - name: Restrict Mosquitto Password File
      ansible.builtin.command: chmod 700 {{ project_source_path }}/mosquitto/config/mosquitto.passwd
