- name: Test Host Connection
  hosts: production
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: "Provisioning"
- name: Test Vars
  hosts: production
  tasks:
    - name: Print message dev_var
      ansible.builtin.debug:
        msg: "test_prod_var: {{ test_prod_var }}"
    - name: Print message all_var
      ansible.builtin.debug:
        msg: "test_all_var: {{ test_all_var }}"
